# Generated by Django 4.1 on 2022-09-15 07:24

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='a_id',
            field=models.UUIDField(default=uuid.UUID('9efc731b-49f9-4652-9a86-dd2cd512fc33'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('3', 'Deleted'), ('2', 'Inactive'), ('1', 'Active')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('e64cbe47-f740-4979-8bf6-8a7f56dba513'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('3', 'Deleted'), ('2', 'Inactive'), ('1', 'Active')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='ebook_id',
            field=models.UUIDField(default=uuid.UUID('3370342d-4f7e-473e-bc31-0e4911bf5cac'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardcopy',
            name='hardCopy_id',
            field=models.UUIDField(default=uuid.UUID('d667fd89-f0f6-4e84-815f-5c52baa7d174'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_id',
            field=models.UUIDField(default=uuid.UUID('fe7fcd96-dff3-47e4-844e-32a93ed9393a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('3', 'Deleted'), ('2', 'Inactive'), ('1', 'Active')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_id',
            field=models.UUIDField(default=uuid.UUID('c10ddc74-aa6e-4b3c-894c-ed696b27ed75'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='status',
            field=models.CharField(choices=[('3', 'Deleted'), ('2', 'Inactive'), ('1', 'Active')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('3', 'User'), ('2', 'Librarian'), ('1', 'Super Admin')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('3', 'Deleted'), ('2', 'Inactive'), ('1', 'Active')], default='2', max_length=1),
        ),
    ]
