# Generated by Django 4.1 on 2022-09-19 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libsystem', '0002_alter_author_a_id_alter_author_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='a_id',
            field=models.UUIDField(default=uuid.UUID('1ca4ceb5-7b8e-4682-8dd8-6c0f2f8b7f39'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('2', 'Inactive'), ('1', 'Active'), ('3', 'Deleted')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('d8e6f87c-334d-4f2c-a1b2-734c9883ca19'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('2', 'Inactive'), ('1', 'Active'), ('3', 'Deleted')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='ebook_id',
            field=models.UUIDField(default=uuid.UUID('365d324a-09fb-485b-98f4-cbb71c024b0d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardcopy',
            name='hardCopy_id',
            field=models.UUIDField(default=uuid.UUID('780fec00-0fc1-4b33-ae3f-95029722c43a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='lang_id',
            field=models.UUIDField(default=uuid.UUID('ed4e8ec6-f30e-4117-8452-090fd0d6a305'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='status',
            field=models.CharField(choices=[('2', 'Inactive'), ('1', 'Active'), ('3', 'Deleted')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_id',
            field=models.UUIDField(default=uuid.UUID('86671fc4-c26c-465d-a061-ca6b0eca3629'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='status',
            field=models.CharField(choices=[('2', 'Inactive'), ('1', 'Active'), ('3', 'Deleted')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Super Admin'), ('2', 'Librarian'), ('3', 'User')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('2', 'Inactive'), ('1', 'Active'), ('3', 'Deleted')], default='2', max_length=1),
        ),
    ]
